DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS phones;

CREATE TABLE users (
  id UUID  PRIMARY KEY NOT NULL,
  email VARCHAR(50) NOT NULL,
  name VARCHAR(200) NOT NULL,
  password VARCHAR(50) NOT NULL,
  created TIMESTAMP NOT NULL,
  modified TIMESTAMP DEFAULT NULL,
  lastLogin TIMESTAMP DEFAULT NULL,
  isactive BOOLEAN NOT NULL,
  token CHARACTER VARYING(500) NOT NULL
);

CREATE TABLE phones (
  id UUID  PRIMARY KEY,
  id_user  UUID NOT NULL,
  number VARCHAR(20)DEFAULT NULL,
  citycode VARCHAR(10) DEFAULT NULL,
  contrycode VARCHAR(10) DEFAULT NULL
);